{
 "title": "Business metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DAU",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "active_users_dau{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAU",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "active_users_dau{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAU",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "active_users_wau{application=\"$application\", instance=\"$instance\", subtype=\"main_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "active_users_wau{application=\"$application\", instance=\"$instance\", subtype=\"avg_dau\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAU",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "active_users_wau{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "active_users_mau{application=\"$application\", instance=\"$instance\", subtype=\"main_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "active_users_mau{application=\"$application\", instance=\"$instance\", subtype=\"avg_dau\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "active_users_mau{application=\"$application\", instance=\"$instance\", subtype=\"main_value\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "active_users_mau{application=\"$application\", instance=\"$instance\", subtype=\"avg_dau\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "active_users_mau{application=\"$application\", instance=\"$instance\", subtype=\"days_count\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}